### ISSUE TITLE
Feature request some mouse shortcuts

### ISSUE THREAD

**Issue by Darkhost1999** [RainbowCookie32/rusty-psn#1]
![FR](https://user-images.githubusercontent.com/60384196/162809932-05913f39-f5ff-4be5-92db-9e93b41ef0a9.jpg)
* Add a Delete context menu. 
* Allow replacing text with right click paste

Reason for request is brought on by this frustration

https://user-images.githubusercontent.com/60384196/162810350-dca7acaf-e8c3-4f5f-90a2-2372dbebd9ea.mp4

Ignore the fact the serial I used does not have updates
I use a mouse and OSK because of a toddler. So mouse shortcuts are kind of essential.
If you're eagle eye you'll see every time I right click the text unhighlights preventing text replacement with the next serial.

**Comment by RainbowCookie32** [comment]
> Add a Delete context menu.

Eh, no harm done in a Clear option on the context menu, shouldn't be too bad.


> every time I right click the text unhighlights preventing text replacement with the next serial.

Idk if i can make egui not deselect the text when right clicking. If I can't, then I'll leave that as is, since a Paste option that unconditionally nukes the existing text is probably more annoying imo.

You can do Ctrl+A, and then Ctrl+V to select all the text and replace with the clipboard's contents.

**Comment by Darkhost1999** [comment]
That should work thanks
