### ISSUE TITLE
Settings window stretches off screen

### ISSUE THREAD

**Issue by vampiregoat699** [RainbowCookie32/rusty-psn#138]
First if you want to change the window where the saves are that is NOT going to happen as when you click the window to change the directory it stretches so far off the screen you can't see the save button or any buttons to save your settings causing it to revert back.[<a href="https://imgur.com/snrDftf"><img src="https://i.imgur.com/snrDftf.png" title="source: imgur.com" /></a>](url)

**Comment by LoScienzo** [comment]
@vampiregoat699 consider renaming the issue to a more helpful title; may i suggest "Settings window unusable: stretches far off-screen"

Here's where the bug is kinda awful 😆
- it's impossible to reduce the height of the settings window by dragging from the top
- it's impossible to drag the "Save" button into view by moving the settings window: you can get right up to the window section which contains the buttons, but that window part is _locked_ outside the visible area of Rusty-PSN, gahh! Torture 😂!

Here is a video showcase
https://github.com/RainbowCookie32/rusty-psn/assets/32672927/d39108b9-3e0f-4d75-8626-2a2631bea127

**Comment by RainbowCookie32** [comment]
Alright, seems like there's a bug somewhere with resizable windows. Can't really go tracking it down right now, so I'll workaround it by making the window a fixed size, see 304a6d5e8c336fcf053c944a6c0f829eafacf56e. Not like the window really needs a lot of space to contain the settings.

It behaves as expected on my size, but you can grab the artifacts [here](https://github.com/RainbowCookie32/rusty-psn/actions/runs/4986558440) when it finishes building.

**Comment by LoScienzo** [comment]
It's definitely fixed 🎉thanks a lot. And yeah it's not crucial for the settings window to be resizable, although i don't know how different monitor resolutions are handled

**Comment by RainbowCookie32** [comment]
Well, I don't know either 😎 

I don't really do anything for different resolutions, just hope egui handles it. So if it ends up being an issue, someone can report it I guess. Will tag a new release with the fix and close the issue

**Comment by RainbowCookie32** [comment]
[Here we go](https://github.com/RainbowCookie32/rusty-psn/releases/tag/v0.3.5), closing as fixed.
