### ISSUE TITLE
using -d won't downlaod to specified location-- Gets deleted from /var/lib/docker

### ISSUE THREAD

**Issue by bundlepax** [RainbowCookie32/rusty-psn#152]
sudo docker run --rm -v ${PWD}/pkgs:/rusty-psn/pkgs rusty-psn -d /home -t BLUS31527

It downloads, then gets deleted from disk.

I needed to sudo chmod -R 777 /var/lib/docker/overlay2
then keep running rsync and hope you don't miss anything while rusty-psn is updating

 rsync -a /var/lib/docker/overlay2 /home/games --info=progress2

then i was able to search which folders are the largest and follow them unitll you find the .pkg files and then install in emulator.

**Comment by RainbowCookie32** [comment]
If you are not using the default path for pkgs, then you should be running `docker run --rm -v /home/:/rusty-psn/pkgs rusty-psn -t BLUS31527`.

The way you are trying to run it, Docker will search for `/home` inside the container, it won't use your home directory. Since it won't find it, it'll get placed on a temporary directory that'll get removed after it's done running.
Using `-v /home/:/rusty-psn/pkgs` instead of `${PWD}/pkgs:/rusty-psn/pkgs` mounts your home directory (the path you were trying to use) to rusty-psn's default download folder for pkgs, which removes the need to specify a path with `-d`.
